// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFqsHVGsdgnppwL_2XkbdK7Y5tBS2WMns',
    appId: '1:252017161143:web:5df41cd8df3534fc42ae32',
    messagingSenderId: '252017161143',
    projectId: 'zorin-fixed-2026',
    authDomain: 'zorin-fixed-2026.firebaseapp.com',
    storageBucket: 'zorin-fixed-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlQVk25KsjM3_kxiS21OXnNkTirMJCpDQ',
    appId: '1:252017161143:android:fec623abd2907a0242ae32',
    messagingSenderId: '252017161143',
    projectId: 'zorin-fixed-2026',
    storageBucket: 'zorin-fixed-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgPMJOIwR3mUnyvgjh8ZuVgWLoOiEUJa0',
    appId: '1:252017161143:ios:3608304d221158a542ae32',
    messagingSenderId: '252017161143',
    projectId: 'zorin-fixed-2026',
    storageBucket: 'zorin-fixed-2026.firebasestorage.app',
    iosBundleId: 'com.example.zorinFixed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBADoKe6-3IDEtWswGignt06gafnMNHDiU',
    appId: '1:212830266450:web:5237b9014e13b02a74ab8b',
    messagingSenderId: '212830266450',
    projectId: 'zorin-ed6c0',
    authDomain: 'zorin-ed6c0.firebaseapp.com',
    storageBucket: 'zorin-ed6c0.firebasestorage.app',
    measurementId: 'G-D4S3NZSYE9',
  );
}